export const SEARCH_PLACES = 'SEARCH_PLACES';
export const SEARCH_PLACES_SUCCESS = 'SEARCH_PLACES_SUCCESS';
export const SEARCH_PLACES_FAILURE = 'SEARCH_PLACES_FAILURE';

export const GET_HISTORY = 'GET_HISTORY';
export const GET_HISTORY_SUCCESS = 'GET_HISTORY_SUCCESS';
export const GET_HISTORY_FAILURE = 'GET_HISTORY_FAILURE';

export const SAVE_HISTORY = 'SAVE_HISTORY';
export const SAVE_HISTORY_SUCCESS = 'SAVE_HISTORY_SUCCESS';
export const SAVE_HISTORY_FAILURE = 'SAVE_HISTORY_FAILURE';

export const REMOVE_HISTORY = 'REMOVE_HISTORY';
export const REMOVE_HISTORY_SUCCESS = 'REMOVE_HISTORY_SUCCESS';
export const REMOVE_HISTORY_FAILURE = 'REMOVE_HISTORY_FAILURE';
